version: "3"

services:
  rsync-client:
    image: npastorale/archmirror-rsync-client
    restart: unless-stopped
    volumes:
      - data:/data

  http-server:
    image: npastorale/archmirror-http-server
    restart: unless-stopped
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: volume
        source: data
        target: /data
        read_only: true

volumes:
  data:
